name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build for all platforms
        run: make build-all

      - name: Create distribution archives
        run: |
          # Create releases directory
          mkdir -p releases

          # macOS Intel
          tar -czf releases/video-gen-darwin-amd64.tar.gz -C dist video-gen-darwin-amd64 LICENSE README.md

          # macOS Apple Silicon
          tar -czf releases/video-gen-darwin-arm64.tar.gz -C dist video-gen-darwin-arm64 LICENSE README.md

          # Linux amd64
          tar -czf releases/video-gen-linux-amd64.tar.gz -C dist video-gen-linux-amd64 LICENSE README.md

          # Linux ARM64
          tar -czf releases/video-gen-linux-arm64.tar.gz -C dist video-gen-linux-arm64 LICENSE README.md

          # Windows
          cd dist
          zip ../releases/video-gen-windows-amd64.zip video-gen-windows-amd64.exe ../LICENSE ../README.md
          cd ..

      - name: Generate checksums
        run: |
          cd releases
          sha256sum *.tar.gz *.zip > checksums.txt
          cat checksums.txt

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          # Extract the changelog section for this version
          awk "/## \[${VERSION}\]/,/## \[/" CHANGELOG.md | sed '$d' > release_notes.md
          cat release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/video-gen-darwin-amd64.tar.gz
            releases/video-gen-darwin-arm64.tar.gz
            releases/video-gen-linux-amd64.tar.gz
            releases/video-gen-linux-arm64.tar.gz
            releases/video-gen-windows-amd64.zip
            releases/checksums.txt
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
